import {$,el,field,option,panel,table,setStatus} from './common/dom.js';import {loadJSON} from './common/data.js';import {readLocal,writeLocal,clearLocal} from './common/state.js';import {downloadJSON,download} from './common/download.js';import {checkAnswer,lessonDraft,updateProgress,progressSummary} from './core.js';
const app=$('#app'),key='sahitya-demo-progress';let progress=readLocal(key,{}),lesson,catalog,activity;
async function main(){catalog=await loadJSON('./data/catalog.json');const lessons=catalog.items.filter(i=>i.kind==='lesson'),activities=catalog.items.filter(i=>i.kind==='activity');const units=[...new Set(lessons.map(l=>l.unit))];const unit=el('select',{id:'unit'},units.map(u=>option(u,u.replaceAll('-',' '))));const choose=el('select',{id:'lesson'});const observation=el('select',{id:'activity'},activities.map(a=>option(a.id,a.title)));
 function choices(){choose.replaceChildren(...lessons.filter(l=>l.unit===unit.value).map(l=>option(l.id,l.title)));}choices();
 async function change(){try{const item=lessons.find(l=>l.id===choose.value);lesson=await loadJSON('./'+item.path);render();setStatus('Example lesson ready for teacher-supported practice.');}catch(e){setStatus(e.message,'error');}}
 unit.addEventListener('change',()=>{choices();change();});choose.addEventListener('change',change);observation.addEventListener('change',async()=>{activity=await loadJSON('./'+activities.find(a=>a.id===observation.value).path);render();});activity=await loadJSON('./'+activities[0].path);
 const reset=el('button',{id:'reset-progress',class:'secondary',text:'Reset local progress',onclick:()=>{progress={};clearLocal(key);render();setStatus('Demo practice history cleared.');}});
 app.append(el('div',{class:'layout'},[el('aside',{},[panel('Curriculum explorer',[field('Teaching unit',unit),field('Lesson',choose),field('Educational observation',observation),reset,el('p',{class:'notice',text:'60 new example lessons. Teacher review is pending; observations do not diagnose dyslexia.'})])]),el('div',{id:'content'})]));await change();
}
function render(){if(!lesson)return;const content=$('#content');content.replaceChildren();const answer=el('select',{id:'answer'},[option('','Choose an answer'),...lesson.quiz.choices.map(w=>option(w,w))]);const result=el('p',{id:'quiz-result',class:'muted'});const check=el('button',{id:'check-answer',text:'Check practice answer',onclick:()=>{try{const correct=checkAnswer(lesson,answer.value);progress=updateProgress(progress,lesson.id,correct);writeLocal(key,progress);render();$('#quiz-result').textContent=correct?'This written-pattern answer matches.':'Try the pattern again with your teacher.';setStatus('Practice attempt saved locally.');}catch(e){setStatus(e.message,'error');}}});
 const steps=el('ol',{class:'compact'},lesson.steps.map(s=>el('li',{},[el('strong',{text:s.label+': '}),s.instruction])));content.append(panel(lesson.title,[el('p',{class:'tag',text:'Level '+lesson.level+' · '+lesson.minutes+' minutes'}),el('ul',{class:'items'},lesson.words.map(w=>el('li',{text:w}))),steps,field(lesson.quiz.prompt,answer),check,result,el('div',{class:'actions'},[el('button',{id:'export-lesson',class:'secondary',text:'Export lesson text draft',onclick:()=>download(lessonDraft(lesson),lesson.id+'.txt')})])]));
 const summary=progressSummary(progress);content.append(panel('Practice history',[table(['Lessons attempted','Attempts','Matching answers'],[[summary.lessons_attempted,summary.attempts,summary.correct]]),el('button',{id:'export-progress',class:'secondary',text:'Export fictional practice JSON',onclick:()=>downloadJSON({id:'SYN-LEARNER-001',project_id:'sahitya-phonics',is_synthetic:true,created_at:new Date().toISOString(),payload:{progress,observation:activity?{activity_id:activity.id,status:$('#observation').value}:null}},'sahitya-practice.json')})]));
 if(activity){const obs=el('select',{id:'observation'},activity.options.map(o=>option(o,o)));content.append(panel(activity.title,[el('p',{text:activity.instruction}),field('Teacher observation',obs),el('p',{class:'muted',text:'Select a support observation for discussion. No clinical classification is produced.'})]));}
}
main().catch(e=>setStatus(e.message,'error'));
